feat: add ability to use AWS KMS backed keys for cert generation
- switch cfssl to plain openssl to allow using openssl engines for kms support
  (tested with https://github.com/gardenlinux/openssl-engine-kms)
- when using local file backed keys gencert outputs .key files
  whereas when using AWS KMS key storage .arn files are output
- subsequent calls to gencert and genefiauth check if the .crt file has a corresponding .key or .arn file
  and will automatically use kms engine or local files accordingly

diff --git a/cert/gencert b/cert/gencert
--- a/cert/gencert
+++ b/cert/gencert
@@ -1,30 +1,47 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -eufo pipefail
+set -Eeufo pipefail
 
-cert_json=cert.json
-conf_json=config.json
-
+conf=
 ca_base=
-
-hostname=
+algo=RSA
+algo_opt=
+aws_kms_key_spec=
+days=3650
+ext_file=
 
 while [ $# -gt 0 ]; do
 	case "$1" in
-		--cert)
-			cert_json="$2"
-			shift 2
-			;;
 		--conf)
-			conf_json="$2"
+			conf="$2"
 			shift 2
 			;;
 		--ca)
 			ca_base="${2%.crt}"
+			if [ -n "$ca_base" ] && [ "$ca_base.crt" != "$2" ]; then
+				echo "CA file must end in .crt" >&2
+				exit 1
+			fi
 			shift 2
 			;;
-		--hostname)
-			hostname="$2"
+		--algorithm)
+			algo="$2"
+			shift 2
+			;;
+		--algorithm-options)
+			algo_opt="$2"
+			shift 2
+			;;
+		--aws-kms-key-spec)
+			aws_kms_key_spec="$2"
+			shift 2
+			;;
+		--days)
+			days="$2"
+			shift 2
+			;;
+		--extensions)
+			ext_file="$2"
 			shift 2
 			;;
 		*)
@@ -33,40 +50,85 @@ while [ $# -gt 0 ]; do
 	esac
 done
 
-base="${1%.crt}"
-name="${base%.*}"
-type="${base##*.}"
-
-function get_type_str {
-	case "$type" in
-		ca) echo CA ;;
-		sign) echo Signature ;;
-		*) tr '[:lower:]' '[:upper:]' <<< "${type:0:1}${type:1}" ;;
-	esac
-}
-
-type_str="$(get_type_str "$type")"
-export CERT_CN="$CERT_NAME_OU $name $type_str"
-
-if [ -z "$ca_base" ]; then
-	echo "Generating self signed $type_str certificate ($CERT_CN) -> $base.crt"
-else
-	echo "Generating $type_str certificate ($CERT_CN), signed by $ca_base.crt -> $base.crt"
+if [ -n "$conf" ]; then
+	while IFS='=' read -r key value; do
+		declare "$key"="$value"
+	done < "$conf"
 fi
 
-case "$type" in
-	ca)
-		cfssl gencert -initca <(envsubst < "$cert_json") | cfssljson -bare "$base"
-		[ -z "$ca_base" ] || cfssl sign -ca "$ca_base.crt" -ca-key "$ca_base.key" -config "$conf_json" -profile intermediate_ca "$base.csr" | cfssljson -bare "$base"
-		;;
-	*)
-		cfssl gencert -ca "$ca_base.crt" -ca-key "$ca_base.key" -config "$conf_json" -profile "$type" ${hostname:+-hostname "$hostname"} <(envsubst < "$cert_json") | cfssljson -bare "$base"
-		;;
-esac
+if [ -z "$algo_opt" ]; then
+	case "$algo" in
+		RSA)
+			algo_opt=rsa_keygen_bits:4096
+			;;
+		*)
+			echo "algorithm options not set and can't be inferred for algorithm $algo" >&2
+			exit 1
+			;;
+	esac
+fi
 
-mv "$base.pem" "$base.crt"
-mv "$base-key.pem" "$base.key"
-rm "$base.csr"
+engine_params=()
+if [ -n "$ca_base" ]; then
+	if [ ! -f "$ca_base.crt" ]; then
+		echo "$ca_base.crt does not exist" >&2
+		exit 1
+	fi
+
+	if [ -f "$ca_base.key" ]; then
+		ca_key_params=(-CAkey "$ca_base.key")
+	elif [ -f "$ca_base.arn" ]; then
+		engine_params+=(-engine kms)
+		ca_key_params=(-CAkeyform engine -CAkey "$(cat "$ca_base.arn")")
+	else
+		echo "neither $ca_base.key nor $ca_base.arn exists, but at least one is required" >&2
+		exit 1
+	fi
+fi
+
+base="${1%.crt}"
+if [ "$base.crt" != "$1" ]; then
+	echo "output file must end in .crt" >&2
+	exit 1
+fi
+
+if [ -z "$aws_kms_key_spec" ]; then
+	echo "Generating $algo private key -> $base.key"
+	openssl genpkey -algorithm "$algo" -pkeyopt "$algo_opt" -out "$base.key"
+
+	key_params=(-key "$base.key")
+else
+	echo "Generating AWS KMS backed $aws_kms_key_spec private key -> $base.arn"
+	aws kms create-key \
+		--description "$CERT_CN" \
+		--key-usage SIGN_VERIFY \
+		--customer-master-key-spec "$aws_kms_key_spec" \
+		--query "KeyMetadata.Arn" \
+		--output text > "$base.arn"
+
+	engine_params+=(-engine kms)
+	key_params=(-keyform engine -key "$(cat "$base.arn")")
+fi
+
+subj="/CN=$CERT_CN/C=$CERT_C/L=$CERT_L/O=$CERT_O/OU=$CERT_OU/emailAddress=$CERT_E/"
+
+ext_opts=()
+if [ -n "$ext_file" ]; then
+	ext_file_path="$(cd "$(dirname "$conf")" && realpath "$ext_file")"
+	while read -r ext; do
+		ext_opts+=(-addext "$ext")
+	done < "$ext_file_path"
+fi
+
+if [ -z "$ca_base" ]; then
+	echo "Generating self signed certificate ($CERT_CN) -> $base.crt"
+	openssl req -new -sha256 "${engine_params[@]}" "${key_params[@]}" -x509 -days "$days" -subj "$subj" "${ext_opts[@]}" -out "$base.crt"
+else
+	echo "Generating certificate ($CERT_CN), signed by $ca_base.crt -> $base.crt"
+	openssl req -new -sha256 "${engine_params[@]}" "${key_params[@]}" -subj "$subj" "${ext_opts[@]}" -out "$base.csr"
+	openssl x509 -sha256 "${engine_params[@]}" -CA "$ca_base.crt" "${ca_key_params[@]}" -set_serial "0x$(openssl rand -hex 8)" -days "$days" -req -in "$base.csr" -out "$base.crt"
+	rm "$base.csr"
+fi
 
 if [ -n "$ca_base" ]; then
 	if [ -f "$ca_base.chain" ]; then
diff --git a/cert/genefiauth b/cert/genefiauth
--- a/cert/genefiauth
+++ b/cert/genefiauth
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -eufo pipefail
+set -Eeufo pipefail
 
 guid=
 ca_base=
@@ -18,6 +18,10 @@ while [ $# -gt 0 ]; do
 			;;
 		--ca)
 			ca_base="${2%.crt}"
+			if [ "$ca_base.crt" != "$2" ]; then
+				echo "CA file must end in .crt" >&2
+				exit 1
+			fi
 			shift 2
 			;;
 		--null)
@@ -42,9 +46,25 @@ case "$type" in
 	kek) type=KEK ;;
 esac
 
+if [ -n "$ca_base" ]; then
+	if [ ! -f "$ca_base.crt" ]; then
+		echo "$ca_base.crt does not exist" >&2
+		exit 1
+	fi
+
+	if [ -f "$ca_base.key" ]; then
+		ca_key_params=(-k "$ca_base.key")
+	elif [ -f "$ca_base.arn" ]; then
+		ca_key_params=(-e kms -k "$(cat "$ca_base.arn")")
+	else
+		echo "neither $ca_base.key nor $ca_base.arn exists, but at least one is required" >&2
+		exit 1
+	fi
+fi
+
 if [ "$null" = 0 ]; then
 	cert-to-efi-sig-list -g "$guid" "$cert" "$base.esl"
-	sign-efi-sig-list -g "$guid" -c "$ca_base.crt" -k "$ca_base.key" "$type" "$base.esl" "$base.auth"
+	sign-efi-sig-list -g "$guid" -c "$ca_base.crt" "${ca_key_params[@]}" "$type" "$base.esl" "$base.auth"
 else
-	sign-efi-sig-list -g "$guid" -c "$ca_base.crt" -k "$ca_base.key" "$type" /dev/null "$base.auth"
+	sign-efi-sig-list -g "$guid" -c "$ca_base.crt" "${ca_key_params[@]}" "$type" /dev/null "$base.auth"
 fi
