refactor: update-syslinux - parse sdboot loader entries to generate config

diff --git a/features/_boot/file.include/usr/local/sbin/update-syslinux b/features/_boot/file.include/usr/local/sbin/update-syslinux
--- a/features/_boot/file.include/usr/local/sbin/update-syslinux
+++ b/features/_boot/file.include/usr/local/sbin/update-syslinux
@@ -2,69 +2,110 @@
 
 set -uoeE pipefail
 
-bootDir="/efi"
-kernelDir="${bootDir}/Default"
 configDir="/etc/kernel/cmdline.d"
-configFile="${bootDir}/syslinux/syslinux.cfg"
+configFile="syslinux/syslinux.cfg"
 
-check_version() {
-	local v=$1
-	if [ ! -d "$kernelDir/$v" ]; then 
+check_config() {
+	local f=$1
+	if [ ! -f "$ESP_PATH/$(get_linux "$f" | cut -c 3-)" ]; then
+	  echo "ce plm"
 		return 1
 	fi
-	if [ ! -f "$kernelDir/$v/linux" ]; then
-		return 1
-	fi
-	if [ ! -f "$kernelDir/$v/initrd.img-$v" ]; then
-		return 1
-	fi
+	for i in $(get_initrd "$f" | tr ',' ' '); do
+	  if [ ! -f "$ESP_PATH/$(echo "$i" | cut -c 3-)" ]; then
+		  return 1
+	  fi
+	done
 	return 0
+}
+
+err() {
+  echo "${@}" >&2
+  exit 1
+}
+
+get_options() {
+	local f=$1
+		options=$(awk '/^options/{ $1=""; print $0 }' "$f")
+	if [ -z "$options" ]; then
+		err "no options detected for $f"
+	fi
+	echo "$options"
+}
+
+get_version() {
+	local f=$1
+	version=$(awk '/^version/{ print $2 }' "$f")
+	if [ -z "$version" ]; then
+		err "no version field detected for $f"
+	fi
+	echo "$version"
+}
+
+get_linux() {
+	local f=$1
+	linux=$(awk '/^linux/{ print ".."$2 }' "$f")
+	if [ -z "$linux" ]; then
+		err "no kernel field detected for $f"
+	fi
+	echo "$linux"
+}
+
+get_initrd() {
+	local f=$1
+	initrd=$(awk '/^initrd/{ print ".."$2 }' "$f" | paste -s -d ',')
+	if [ -z "$initrd" ]; then
+		err "no initrd field detected for $f"
+	fi
+	echo "$initrd"
 }
 
 if ! which syslinux &> /dev/null; then
 	exit 0
 fi
 
-#TODO: detect if anything other than bootDir/Default is used
-if [ ! -d "$kernelDir" ]; then
-        exit 0
-fi 
+if [ -z "${ESP_PATH:-}" ]; then
+  ESP_PATH=$(bootctl -p || err "cannot detect ESP, check if ESP is mounted on /efi or /boot/efi")
+fi
 
-# load extras
 for i in "${configDir}"/*-*.cfg; do
 	[ -e "$i" ] || continue
+	# shellcheck disable=SC1090
 	source "$i"
 done
 
-versions=()
+configs=()
 # kernel / initrd
-for kernel in /boot/vmlinuz-*; do 
-	if check_version "${kernel#*-}"; then
-		versions+=("${kernel#*-}")
+for config in "${ESP_PATH}"/loader/entries/*.conf*; do
+	if check_config "$config"; then
+		configs+=("${config}")
+	else
+		err "kernel or initrd doesn't exist for $config"
 	fi
 done
 
-if [ "${#versions[@]}" == "0" ]; then
-	echo "no valid kernels found" 1>&2
-	exit 1
+
+if [ "${#configs[@]}" == "0" ]; then
+  err "no valid configs found under $ESP_PATH/loader/entries"
 fi
 
-readarray -t vSorted < <(printf '%s\n' "${versions[@]}" | sort -rV)
+readarray -t vSorted < <(printf '%s\n' "${configs[@]}" | sort -rV)
 {
+  echo "# automatically generated by update-syslinux"
 	echo "UI menu.c32"
 	echo "PROMPT 0"
 	echo
-	echo "MENU TITLE Gardenlinux" 
+	echo "MENU TITLE Gardenlinux"
 	echo "TIMEOUT $TIMEOUT"
-	echo "DEFAULT ${vSorted[0]}" 
+	echo "DEFAULT Linux-$(get_version "${vSorted[0]}")"
 	echo
 	for v in "${vSorted[@]}"; do
-		echo "LABEL Linux $v"
-		echo " LINUX ../Default/$v/linux"
-		echo " APPEND root=${DEVICE} ${CMDLINE_LINUX}"
-		echo " INITRD ../Default/${v}/initrd.img-$v"
+		echo "LABEL Linux-$(get_version "$v")"
+		echo " LINUX $(get_linux "$v")"
+		echo " APPEND $(get_options "$v")"
+		echo " INITRD $(get_initrd "$v")"
 		echo
 	done
-} > "${configFile}.new" 
+} > "${ESP_PATH}/${configFile}.new"
 
-mv "${configFile}.new" "${configFile}"
+mv "${ESP_PATH}/${configFile}.new" "${ESP_PATH}/${configFile}"
