Streamline GitHub workflow release target logic
Signed-off-by: Tobias Wolf <wolf@b1-systems.de>

diff --git a/.github/workflows/publish_oci_containers.yml b/.github/workflows/publish_oci_containers.yml
--- a/.github/workflows/publish_oci_containers.yml
+++ b/.github/workflows/publish_oci_containers.yml
@@ -12,6 +12,9 @@ on:
       version:
         type: string
         required: true
+      target:
+        type: string
+        required: true
       flavors_matrix:
         type: string
         required: true
@@ -21,12 +24,6 @@ on:
       original_workflow_name:
         type: string
         default: ''
-      repository:
-        type: string
-        required: true
-      signing_env:
-        type: string
-        required: true
     secrets:
       aws_role:
         required: true
@@ -39,7 +36,24 @@ on:
 env:
   GLCLI_VERSION: 0.6.4
 jobs:
+  determine_repository:
+    name: Determine release repository to use for target ${{ inputs.target }}
+    runs-on: ubuntu-latest
+    outputs:
+      repository: ${{ steps.set_repository.outputs.repository }}
+    steps:
+      - id: set_repository
+        run: |
+          if [[ "${{ inputs.target }}" == "release" ]]; then
+            echo "repository=ghcr.io/gardenlinux/gardenlinux" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ inputs.target }}" == "nightly" ]]; then
+            echo "repository=ghcr.io/gardenlinux/nightly" >> "$GITHUB_OUTPUT"
+          else
+            echo "invalid release target ${{ inputs.target }}" >&2
+            exit 1
+          fi
   container:
+    needs: determine_repository
     name: Publish container base image
     runs-on: ubuntu-24.04
     defaults:
@@ -83,41 +97,42 @@ jobs:
 
           # Tagging for amd64 nightly
           if [ $is_nightly = true ]; then
-            podman tag "$image" ${{ inputs.repository }}:amd64-nightly
-            podman push ${{ inputs.repository }}:amd64-nightly
+            podman tag "$image" ${{ needs.determine_repository.outputs.repository }}:amd64-nightly
+            podman push ${{ needs.determine_repository.outputs.repository }}:amd64-nightly
           fi
 
           # Tagging for amd64 with version
-          podman tag "$image" ${{ inputs.repository }}:amd64-${version}
-          podman push ${{ inputs.repository }}:amd64-${version}
+          podman tag "$image" ${{ needs.determine_repository.outputs.repository }}:amd64-${version}
+          podman push ${{ needs.determine_repository.outputs.repository }}:amd64-${version}
 
           tar xzv < "${CNAME_ARM64}.tar.gz"
           image="$(podman load < ${CNAME_ARM64}.oci | awk '{ print $NF }')"
 
           # Tagging for arm64 nightly
           if [ $is_nightly = true ]; then
-            podman tag "$image" ${{ inputs.repository }}:arm64-nightly
-            podman push ${{ inputs.repository }}:arm64-nightly
+            podman tag "$image" ${{ needs.determine_repository.outputs.repository }}:arm64-nightly
+            podman push ${{ needs.determine_repository.outputs.repository }}:arm64-nightly
           fi
 
           # Tagging for arm64 with version
-          podman tag "$image" ${{ inputs.repository }}:arm64-${version}
-          podman push ${{ inputs.repository }}:arm64-${version}
+          podman tag "$image" ${{ needs.determine_repository.outputs.repository }}:arm64-${version}
+          podman push ${{ needs.determine_repository.outputs.repository }}:arm64-${version}
 
           # Creating and pushing manifest for nightly
           if [ $is_nightly = true ]; then
-            podman manifest create ${{ inputs.repository }}:nightly
-            podman manifest add ${{ inputs.repository }}:nightly ${{ inputs.repository }}:amd64-nightly
-            podman manifest add ${{ inputs.repository }}:nightly ${{ inputs.repository }}:arm64-nightly
-            podman manifest push ${{ inputs.repository }}:nightly
+            podman manifest create ${{ needs.determine_repository.outputs.repository }}:nightly
+            podman manifest add ${{ needs.determine_repository.outputs.repository }}:nightly ${{ needs.determine_repository.outputs.repository }}:amd64-nightly
+            podman manifest add ${{ needs.determine_repository.outputs.repository }}:nightly ${{ needs.determine_repository.outputs.repository }}:arm64-nightly
+            podman manifest push ${{ needs.determine_repository.outputs.repository }}:nightly
           fi
 
           # Creating and pushing manifest for version tag
-          podman manifest create ${{ inputs.repository }}:${version}
-          podman manifest add ${{ inputs.repository }}:${version} ${{ inputs.repository }}:amd64-${version}
-          podman manifest add ${{ inputs.repository }}:${version} ${{ inputs.repository }}:arm64-${version}
-          podman manifest push ${{ inputs.repository }}:${version}
+          podman manifest create ${{ needs.determine_repository.outputs.repository }}:${version}
+          podman manifest add ${{ needs.determine_repository.outputs.repository }}:${version} ${{ needs.determine_repository.outputs.repository }}:amd64-${version}
+          podman manifest add ${{ needs.determine_repository.outputs.repository }}:${version} ${{ needs.determine_repository.outputs.repository }}:arm64-${version}
+          podman manifest push ${{ needs.determine_repository.outputs.repository }}:${version}
   bare_flavors:
+    needs: determine_repository
     name: Publish bare flavors
     if: ${{ inputs.bare_flavors_matrix != '{"include":[]}' }}
     runs-on: ubuntu-24.04
@@ -150,42 +165,43 @@ jobs:
           image="$(podman load < ${{ matrix.config }}-amd64.oci | awk '{ print $NF }')"
 
           # Tagging and pushing amd64 with version
-          podman tag "$image" ${{ inputs.repository }}/bare-${{ matrix.config }}:amd64-$version
-          podman push ${{ inputs.repository }}/bare-${{ matrix.config }}:amd64-$version
+          podman tag "$image" ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:amd64-$version
+          podman push ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:amd64-$version
 
           # Tagging and pushing amd64 with nightly
           if [ $is_nightly = true ]; then
-            podman tag "$image" ${{ inputs.repository }}/bare-${{ matrix.config }}:amd64-nightly
-            podman push ${{ inputs.repository }}/bare-${{ matrix.config }}:amd64-nightly
+            podman tag "$image" ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:amd64-nightly
+            podman push ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:amd64-nightly
           fi
 
           # Handling arm64 image
           image="$(podman load < ${{ matrix.config }}-arm64.oci | awk '{ print $NF }')"
 
           # Tagging and pushing arm64 with version
-          podman tag "$image" ${{ inputs.repository }}/bare-${{ matrix.config }}:arm64-$version
-          podman push ${{ inputs.repository }}/bare-${{ matrix.config }}:arm64-$version
+          podman tag "$image" ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:arm64-$version
+          podman push ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:arm64-$version
 
           # Tagging and pushing arm64 with nightly
           if [ $is_nightly = true ]; then
-            podman tag "$image" ${{ inputs.repository }}/bare-${{ matrix.config }}:arm64-nightly
-            podman push ${{ inputs.repository }}/bare-${{ matrix.config }}:arm64-nightly
+            podman tag "$image" ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:arm64-nightly
+            podman push ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:arm64-nightly
           fi
 
           # Creating and pushing manifest for version tag
-          podman manifest create ${{ inputs.repository }}/bare-${{ matrix.config }}:$version
-          podman manifest add ${{ inputs.repository }}/bare-${{ matrix.config }}:$version ${{ inputs.repository }}/bare-${{ matrix.config }}:amd64-$version
-          podman manifest add ${{ inputs.repository }}/bare-${{ matrix.config }}:$version ${{ inputs.repository }}/bare-${{ matrix.config }}:arm64-$version
-          podman manifest push ${{ inputs.repository }}/bare-${{ matrix.config }}:$version
+          podman manifest create ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:$version
+          podman manifest add ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:$version ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:amd64-$version
+          podman manifest add ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:$version ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:arm64-$version
+          podman manifest push ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:$version
 
           # Creating and pushing manifest for nightly tag
           if [ $is_nightly = true ]; then
-            podman manifest create ${{ inputs.repository }}/bare-${{ matrix.config }}:nightly
-            podman manifest add ${{ inputs.repository }}/bare-${{ matrix.config }}:nightly ${{ inputs.repository }}/bare-${{ matrix.config }}:amd64-nightly
-            podman manifest add ${{ inputs.repository }}/bare-${{ matrix.config }}:nightly ${{ inputs.repository }}/bare-${{ matrix.config }}:arm64-nightly
-            podman manifest push ${{ inputs.repository }}/bare-${{ matrix.config }}:nightly
+            podman manifest create ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:nightly
+            podman manifest add ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:nightly ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:amd64-nightly
+            podman manifest add ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:nightly ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:arm64-nightly
+            podman manifest push ${{ needs.determine_repository.outputs.repository }}/bare-${{ matrix.config }}:nightly
           fi
   push_flavors:
+    needs: determine_repository
     name: Publish flavors
     runs-on: ubuntu-24.04
     defaults:
@@ -196,7 +212,7 @@ jobs:
     permissions:
       id-token: write
       packages: write
-    environment: ${{ inputs.signing_env }}
+    environment: ${{ inputs.target == 'release' && 'oidc_aws_kms_release' || 'oidc_aws_kms_nightly' }}
     strategy:
       fail-fast: false
       matrix: ${{ fromJson(inputs.flavors_matrix) }}
@@ -247,7 +263,7 @@ jobs:
           retry_count=0
           exit_code=0
           until [ $retry_count -ge $max_retries ]; do
-            if output=$(GLOCI_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }} GLOCI_REGISTRY_USERNAME=${{ github.repository_owner }} python /opt/glcli/src/glcli.py push-manifest --dir "$CNAME" --container ${{ inputs.repository }} --arch ${{ matrix.arch }} --version ${{ inputs.version }} --cname "$CNAME" --cosign_file digest.txt --manifest_file "oci_manifest_entry_$CNAME.json" 2>&1); then
+            if output=$(GLOCI_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }} GLOCI_REGISTRY_USERNAME=${{ github.repository_owner }} python /opt/glcli/src/glcli.py push-manifest --dir "$CNAME" --container ${{ needs.determine_repository.outputs.repository }} --arch ${{ matrix.arch }} --version ${{ inputs.version }} --cname "$CNAME" --cosign_file digest.txt --manifest_file "oci_manifest_entry_$CNAME.json" 2>&1); then
               cat digest.txt
               exit 0
             elif echo "$output" | grep -q "Bad Gateway"; then
@@ -267,10 +283,10 @@ jobs:
       - name: Sign the manifest
         run: |
           docker login ghcr.io -u token -p ${{ github.token }}
-          cosign sign -tlog-upload=false --key awskms://kms.${{ secrets.aws_region }}.amazonaws.com/${{ secrets.oci_kms_arn }} ${{ inputs.repository }}@$(cat digest.txt)
+          cosign sign -tlog-upload=false --key awskms://kms.${{ secrets.aws_region }}.amazonaws.com/${{ secrets.oci_kms_arn }} ${{ needs.determine_repository.outputs.repository }}@$(cat digest.txt)
       - name: Verify signature
         run: |
-          cosign verify --insecure-ignore-tlog=true --key awskms://kms.${{ secrets.aws_region}}.amazonaws.com/${{ secrets.oci_kms_arn }} ${{ inputs.repository }}@$(cat digest.txt)
+          cosign verify --insecure-ignore-tlog=true --key awskms://kms.${{ secrets.aws_region}}.amazonaws.com/${{ secrets.oci_kms_arn }} ${{ needs.determine_repository.outputs.repository }}@$(cat digest.txt)
       - uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # pin@v4.2.3
         with:
           path: oci_manifest_entry_${{ env.CNAME }}.json
@@ -315,7 +331,7 @@ jobs:
           mkdir -p "manifests"
           mv "oci_manifest_entry_$CNAME.json" "manifests/"
   update_manifest_index:
-    needs: aggregate_oci_manifests
+    needs: [ determine_repository, aggregate_oci_manifests ]
     name: Update OCI manifest index
     runs-on: ubuntu-24.04
     defaults:
@@ -346,4 +362,4 @@ jobs:
           pip install -r /opt/glcli/requirements.txt
       - name: Update index using glcli tool
         run: |
-          GLOCI_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }} GLOCI_REGISTRY_USERNAME=${{ github.repository_owner }} python /opt/glcli/src/glcli.py update-index --container ${{ inputs.repository }} --version ${{ inputs.version }} --manifest_folder manifests
+          GLOCI_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }} GLOCI_REGISTRY_USERNAME=${{ github.repository_owner }} python /opt/glcli/src/glcli.py update-index --container ${{ needs.determine_repository.outputs.repository }} --version ${{ inputs.version }} --manifest_folder manifests
